### ISSUE TITLE
Improve skylink param handling

### ISSUE THREAD

**Issue by interstella-5555** [NebulousLabs/skynet-js#1]
Improve `skylink` param handling:

- validate skylink `[a-zA-Z0-9_-]{46}`
- allow `sia://<skylink>` (strip `sia://`)

**Comment by anthg** [comment]
I'd love to help out with this as a first issue if someone is willing to talk me through it in a bit more detail

**Comment by interstella-5555** [comment]
Thanks @anthg ! So the idea is that we should add validation to https://github.com/NebulousLabs/skynet-js/blob/master/src/index.js#L75 param `skylink`.
> it should try to match to `[a-zA-Z0-9_-]{46}` 

or 

> it should match `[a-zA-Z0-9_-]{46}` prefixed with `sia://` and then extract just the 46 characters skylink part (without `sia://`).

It should throw a meaningful error otherwise and we should have unit tests for that. 

We also have two other functions https://github.com/NebulousLabs/skynet-js/blob/master/src/index.js#L63 and https://github.com/NebulousLabs/skynet-js/blob/master/src/index.js#L69 that accept `skylink` as a param but since the first they do is they call `getUrl` then a simple test that asserts that they indeed call `getUrl` would suffice.

Then once it's all done, we should probably put a note about the possibility to pass the skylink with `sia://` prefix to README.md for the documentation to update.

Let me know how does it sound to you :)
