### ISSUE TITLE
v2.1.1 uploadFile returning undefined

### ISSUE THREAD

**Issue by Delivator** [NebulousLabs/skynet-js#112]
Using the code from the SDK documentation 
```js
async function uploadExample() {
  try {
    const { skylink } = await client.uploadFile(file);
  } catch (error) {
    console.log(error)
  }
}
```
return undefined on successful upload

**Comment by Delivator** [comment]
Looks like it works with out the curly braces around skylink, eg.: `const skylink = await client.uploadFile(file);`
So the documentation is just outdated.

**Comment by mrcnski** [comment]
Good catch, thanks 👍 Fixed
