### ISSUE TITLE
parseSkylink should return null on not found

### ISSUE THREAD

**Issue by mrcnski** [NebulousLabs/skynet-js#143]
From https://github.com/NebulousLabs/skynet-js/pull/141#discussion_r512120269.

**Comment by mrcnski** [comment]
This would be a breaking change and I'm not sure what the benefit is. @kwypchlo

**Comment by interstella-5555** [comment]
readability, ie. use case where you want to find a valid skylink in an array of strings (real life use case from handshake api):

```javascript
const validSkylink = array.find((element) => {
  try {
    return parseSkylink(element);
  } catch {
    return false;
  }
})
```

vs

```javascript
const validSkylink = array.find((element) => parseSkylink(element));
```
