### ISSUE TITLE
Add support for production build

### ISSUE THREAD

**Issue by mrcnski** [NebulousLabs/skynet-js#145]
We could add support for production build that would allow people to use https://unpkg.com/

https://github.com/NebulousLabs/skynet-js/pull/131#issuecomment-716569990

**Comment by michielpost** [comment]
Yes, I'd really like to have a production ready minified version of the skynet-js library.

I started my project for the hackathon today, but got stuck in the whole npm/webpack ecosystem mess. If there is a simple `skynet-js.min.js` that I can include using a script tag, it would be so much easier to start a new project.

**Comment by dghelm** [comment]
@michielpost It's not ideal, but in the meantime, you can use this non-minified js file for importing by script tag.

[skynet-js.js](https://siasky.net/_AIIPcUvtd_Y3LtJqGi6JyBfDTB5q-DU6cTqOMTSUil5ww)

For accessing it in browser JS, create a client using
`const client = new skynet.SkynetClient('https://siasky.net');`
or, leave out any arguments to default to the skynet portal your app is deployed on.

It works on codepen at least, so if you run into issues, let me know!

**Comment by michielpost** [comment]
Thanks! Another workaround I just found is using Sky-ID: https://github.com/DaWe35/SkyID#install
It allows easy installation with a script tag and it includes SkyDB under the hood with proxy methods.

**Comment by mrcnski** [comment]
Closing in flavor of https://github.com/SkynetHQ/skynet-js/issues/2

(PS we have a production build at siasky.net/hns/skynet-js/3.0/index.js)
