### ISSUE TITLE
new method request: getRegistryEntryUrl

### ISSUE THREAD

**Issue by interstella-5555** [NebulousLabs/skynet-js#168]
I need to print a url after creating the registry entry. Currently I do it like this:

```javascript
const encodedPublicKey = encodeURIComponent(`ed25519:${publicKey}`);
const encodedDataKey = encodeURIComponent(Buffer.from(HashDataKey(dataKey)).toString("hex"));

console.log(`https://siasky.net/skynet/registry?publickey=${encodedPublicKey}&datakey=${encodedDataKey}`);
```

I would like a function called `getRegistryEntryUrl` that would allow me to modify the above code to be
```javascript
console.log(skynetClient.registry.getEntryUrl(publicKey, dataKey));
```

**Comment by mrcnski** [comment]
I don't see why this would be part of the API. Personally I don't think it should be. Might add it later but it's not a priority item.

**Comment by interstella-5555** [comment]
@m-cat the issues are
- `hashDataKey` is not exported, I had to import from `crypto.js` directly to work around it
- I had to install `Buffer` package
- I had to manually add `ed25519:` prefix to public key that is not documented anywhere

This url allows to read data from registry, it has the same functionality as reading content from skylink and we have `getSkylinkUrl` method.
