### ISSUE TITLE
genKeyPairFromSeed() returns bytearray instead of HEX

### ISSUE THREAD

**Issue by DaWe35** [NebulousLabs/skynet-js#178]
genKeyPairFromSeed() returns something weird bytearray instead of HEX

Solution: Use [this function](https://stackoverflow.com/questions/34309988/byte-array-to-hex-string-conversion-in-javascript) instead of .toString('hex')

**Comment by ilkamo** [comment]
Also the `setJSON` method doesn't work as expected (**v2.6.0**).

![Screenshot 2020-11-10 at 14 20 00](https://user-images.githubusercontent.com/1657091/98679686-ae1e8380-2360-11eb-96d7-f0258b78ecf8.png).

**Comment by mrcnski** [comment]
Thanks @kamy22 , I think this (https://github.com/NebulousLabs/skynet-js/pull/181) by @DaWe35 should have fixed that. We'll be releasing a new version after https://github.com/NebulousLabs/skynet-js/pull/180 is merged.
