### ISSUE TITLE
Reorganize utils

### ISSUE THREAD

**Issue by mrcnski** [NebulousLabs/skynet-js#183]
The `utils.ts` file is stuffed with a bunch of different functions by this point. I think it would be itneresting to organize them into a `utils` directory with different files (for example, theres a few functions for manipulating URLs that can go into `utils/url.ts`).

**Comment by emersonmacro** [comment]
Hello, I'm new to Skynet but I'm interested in getting more involved. Made a PR for this issue - feedback welcome.

**Comment by mrcnski** [comment]
Closed in #364
