### ISSUE TITLE
Encrypted upload/download is not encrypted

### ISSUE THREAD

**Issue by DaWe35** [NebulousLabs/skynet-js#192]
I think the required skykeyName is just ignored when uploading encrypted file.
https://siasky.net/docs/?javascript--browser#uploading-with-encryption

(Would be great to be able to encrypt SkyDB JSON files also)

**Comment by mrcnski** [comment]
From the linked example:

```
// NOTE: this feature has not yet been implemented for this SDK.
```

I'm not sure if we even will implement this since skykeys are not supported on public portals. We will probably do client-side skykeys in the SDK but we don't have concrete plans yet.

**Comment by DaWe35** [comment]
Feel to free to close
