### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by interstella-5555** [NebulousLabs/skynet-js#2]
Add typescript support.

**Comment by acrylix** [comment]
hey there @kwypchlo!

are you guys looking for typescript definitions or having the source implementation done in .ts?

**Comment by interstella-5555** [comment]
Hello @acrylix 👋 It's a small library so I am leaning towards writing it in ts natively.

**Comment by interstella-5555** [comment]
Closed by https://github.com/NebulousLabs/skynet-js/pull/100
