### ISSUE TITLE
add revision parameter to registry.getEntry()

### ISSUE THREAD

**Issue by biggestsombrero8** [NebulousLabs/skynet-js#301]
Hello,

Can you add the capability to call registry.getEntry() with a specific `revision` to the Browser JS SDK?

Currently getEntry() can be called with the `dataKey` only

**Comment by biggestsombrero8** [comment]
Actually it would be more useful to me in the SkyDB API:
 `getJSON(publicKey=.., dataKey='survey'.., revision=42)` to get the JSON from a specific `revision`.

**Comment by m-cat** [comment]
Hi @biggestsombrero8! Unfortunately you cannot get entries from specific revision numbers. SkyDB is not a versioned database in that sense. I apologize for the confusion -- I just noticed that the docs were misleading; I have updated them [here](https://siasky.net/docs/#registry).

Closing for now, but if you have any questions please let me know!
