### ISSUE TITLE
Add method to client for identifying current Skynet portal URL

### ISSUE THREAD

**Issue by dghelm** [NebulousLabs/skynet-js#302]
We need a way for Skapps to reliably know what web portal they're being accessed through.

This will need to use headers the portal passes or an endpoint accessible even when at an HNS subdomain. The first seems far preferable.

**Comment by mrcnski** [comment]
Waiting on https://github.com/NebulousLabs/skynet-webportal/issues/423

> This will need to use headers the portal passes or an endpoint accessible even when at an HNS subdomain. The first seems far preferable.

I think the second option is preferable. The endpoint can return more info in the future -- e.g. sia version

**Comment by dghelm** [comment]
I thought it seemed better, but there are skapps using CNAMEs for bringing their own domain name. Then, endpoint is unknowable without knowing what portal is serving the skapp.

**Comment by mrcnski** [comment]
> there are skapps using CNAMEs for bringing their own domain name.

You're gonna have to explain this to me. I'm not familiar with webdev acronyms

**Comment by dghelm** [comment]
So basically it's where you serve a website from another URL address.

For example, http://dghelm.hns.to/ would have no idea what portal was hosting it based on its own URL. I've seen `skyspaces.io` used before and I think redsolver plans to use `skyfeed.social` for onboarding new users as well (although right now it just redirects).

**Comment by mrcnski** [comment]
Wouldn't the endpoint just be redirected to the same endpoint on the other server? If I'm on a skapp running out of `<skylink>.hns.dghelm.net` then I should be able to also access `dghelm.net/hns/<skylink>` and by the same token `<skylink>hns.dghelm.net/info` or whatever we call it.

**Comment by dghelm** [comment]
AFAIK [http://dghelm.hns.to/](http://dghelm.hns.to/) is a (static) skapp, loading a skyfile from siasky.net, but none of our normal endpoints (like HNS) work, because that route is handled differently by their server.

I think we may just want to use both, but we should keep in mind that we're increasingly creating reserved words when we make endpoints that take precedence over the folder names that skapps using subdomains can use.

**Comment by mrcnski** [comment]
Gotcha, I see the issue now.

> I think we may just want to use both, but we should keep in mind that we're increasingly creating reserved words when we make endpoints that take precedence over the folder names that skapps using subdomains can use.

I feel we should document all these reserved folder names somewhere.

Maybe one day we can develop a static skapp linter to catch stuff like "invalid folder name" 😀

**Comment by mrcnski** [comment]
CLOSED VIA #376
