### ISSUE TITLE
build pipeline overwrites Babel output with tsc

### ISSUE THREAD

**Issue by dghelm** [NebulousLabs/skynet-js#374]
Currently `build` runs babel and then tsc to generate `.js` files.  tsc actually overwrites the babel generated files, meaning we should either:

1. Add `"emitDeclarationOnly": true,` to `tsconfig.build.json` as addressed [here](https://www.typescriptlang.org/docs/handbook/babel-with-typescript.html).
2. Remove Babel from the build process, since we're not using a mixed JS/TS codebase (and since we haven't been using it for npm for quite awhile.)

**Comment by mrcnski** [comment]
Closing in flavor of https://github.com/SkynetHQ/skynet-js/issues/9
