### ISSUE TITLE
Do not set https://siasky.net as a default portal

### ISSUE THREAD

**Issue by interstella-5555** [NebulousLabs/skynet-js#38]
It is easy to obscure the otherwise explicit definition of the portal if we make our portal a default. This could cause bad user experience if people start relying on https://siasky.net free service as a de facto way to use the library and our portal starts having problems or we take it down for updates or sth. We should include it in the examples but the actual library should stay portal agnostic.

@m-cat FLW: the same should apply to all our SDKs

_Originally posted by @kwypchlo in https://github.com/NebulousLabs/skynet-js/pull/37#discussion_r456555386_

**Comment by DavidVorick** [comment]
I think that we should have siasky.net be the default portal. We should strive not to take it down. SDK should be configurable so the dev can choose another portal if they want, but definitely siasky.dev should be the default for a clean and easy user experience.

**Comment by mrcnski** [comment]
Discussed on Discord
