### ISSUE TITLE
Include the new functions in usage examples

### ISSUE THREAD

**Issue by interstella-5555** [NebulousLabs/skynet-js#39]
FLW: We should include the new functions in README.md examples

_Originally posted by @kwypchlo in https://github.com/NebulousLabs/skynet-js/pull/37#issuecomment-660221457_

**Comment by mrcnski** [comment]
I think the README should instead link to the SDK documentation which will be more organized and cover all the functions in depth. In the README we could have a couple quickstart examples but any code samples will need to be maintained and there's a high chance they become forgotten and outdated.

**Comment by interstella-5555** [comment]
If you have the whole documentation in the separate place then please link it in the README.md and it's going to be good enough 👍
