### ISSUE TITLE
Method to detect if user is using a portal account

### ISSUE THREAD

**Issue by dghelm** [NebulousLabs/skynet-js#395]
Pending either a response header or an API endpoint on Web Portal:
[https://github.com/NebulousLabs/skynet-webportal/issues/657](https://github.com/NebulousLabs/skynet-webportal/issues/657)

Skapps that expect their storage to be "long-term" may want to indicate to users that they are not logged into the portal using an account. Even "free" should be fine.

**Comment by mrcnski** [comment]
Closing in flavor of https://github.com/SkynetHQ/skynet-js/issues/21
