### ISSUE TITLE
Base32 encoding and hns subdomains support

### ISSUE THREAD

**Issue by interstella-5555** [NebulousLabs/skynet-js#93]
We introduced 2 new features recently:

### Base32 skylink subdomain access
You can reencode skylink with Base32 and use it as a subdomain to access your content on siasky.net:

- Regular skylink: https://siasky.net/XABvi7JtJbQSMAcDwnUnmp2FKDPjg8_tTTFP4BwMSxVdEg
- Base32 skylink in subdomain: https://bg06v2tidkir84hg0s1s4t97jaeoaa1jse1svrad657u070c9calq4g.siasky.net

Converter: https://convert-skylink.hns.siasky.net/ (conversion explained and documented on [GitHub](https://github.com/kwypchlo/base32))

We should add support to either return regular skylink url or the subdomain skylink url when returning skylink url in SDK. preferably regular skylink url by default and subdomain skylink url if some optional param is set to `true`.

We should also add a utility function that converts Base64 (regular) skylink (46 chars) to Base32 skylink. There are already decoder and encoder functions here https://github.com/kwypchlo/base32/blob/master/src/crypto.ts and usage example is https://github.com/kwypchlo/base32/blob/master/src/App.tsx#L24-L25 but I guess it could be one function in the SDK (instead of two).

### Handshake subdomain access
You can access your content bound to the hns domain using *.hns.siasky.net subdomain:

Regular hns: https://siasky.net/hns/convert-skylink/
New hns subdomain: https://convert-skylink.hns.siasky.net/

We should add a param to function that return hns url to either return regular one (default) or the one in subdomain (optional param set to `true`).

**Comment by mrcnski** [comment]
Clarification: we always pass base64 to `downloadFile`. However we may want it to return base32 subdomain format, which is what the `subdomain` parameter is for. We also want a `subdomain` option for `parseSkylink` even though the SDK does not accept that format, since `parseSkylink` can be used outside the SDK.
